/**
 * IMAGE SUPPORT (VISION)
 * =========================
 * Claude's vision works by adding an "image" content block alongside a
 * "text" block in a user message. Groq's vision-capable models (not
 * llama-3.1-8b-instant — that one's text-only; we use
 * meta-llama/llama-4-scout-17b-16e-instruct here) use the OpenAI-style
 * shape instead: { type: "image_url", image_url: { url } } — and
 * usefully, `url` can be either a real HTTP URL OR a base64 data URI
 * (data:image/png;base64,...), so we don't need Claude's separate
 * { type: "base64", media_type, data } structure — one field does both.
 *
 * marbles.png (11 marbles, generated by
 * vision-sandbox/generate-marbles.mjs so the true count is exactly
 * known) is used to reproduce the lesson's own experiment: a naive
 * prompt undercounts, and a step-by-step methodology prompt is supposed
 * to fix it.
 *
 * HONEST RESULT: on Claude, the lesson's step-by-step prompt fixes the
 * miscount. On this Groq vision model, it did NOT reliably fix it in
 * our test — the model correctly listed all 11 marbles in its own
 * "Method 1", then second-guessed itself down to 10 anyway. This is a
 * real, useful thing to know: prompting techniques that work on one
 * vision model don't automatically transfer to a smaller/different one
 * — you have to verify with your own evals, not assume the lesson's
 * result carries over.
 */

import 'dotenv/config';
import Groq from 'groq-sdk';
import fs from 'node:fs';

const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });
const VISION_MODEL = 'meta-llama/llama-4-scout-17b-16e-instruct';

function imageToDataUrl(path) {
  const bytes = fs.readFileSync(path);
  return `data:image/png;base64,${bytes.toString('base64')}`;
}

async function askAboutImage(imagePath, prompt, options = {}) {
  const response = await groq.chat.completions.create({
    model: VISION_MODEL,
    max_tokens: 1500,
    temperature: options.temperature ?? 1.0,
    messages: [
      {
        role: 'user',
        content: [
          { type: 'image_url', image_url: { url: imageToDataUrl(imagePath) } },
          { type: 'text', text: prompt },
        ],
      },
    ],
  });
  return response.choices[0].message.content;
}

async function main() {
  const imagePath = './vision-sandbox/marbles.png';
  console.log('True count: 11 marbles (fixed positions, see generate-marbles.mjs)\n');

  console.log('=== Naive prompt ===');
  const naive = await askAboutImage(imagePath, 'How many marbles are in this image?');
  console.log(naive);

  console.log('\n=== Step-by-step methodology prompt ===');
  const guided = await askAboutImage(
    imagePath,
    `Analyze this image of marbles and determine the exact count using this methodology:
1. Begin by identifying each unique marble one at a time, describing its color and approximate position. Assign each a number as you identify it.
2. Verify your result by counting with a different method: start from the top-left corner and scan row by row, left to right.

What is the exact, verified number of marbles in this image?`,
    { temperature: 0.3 }
  );
  console.log(guided);
}

main();
